### withYaml
POST http://localhost:8080
---
id: 1

### withJson
POST http://localhost:8080
{
  "id": 1
}

### withEnforcedYaml
POST http://localhost:8080
Content-Type: application/x-yaml
---
id: 1

### withEnforcedYamlAndLowercaseHeader
POST http://localhost:8080
content-type: application/x-yaml
---
id: 1

### withEnforcedYamlAlternativeContentType
POST http://localhost:8080
Content-Type: text/yaml
---
id: 1